### ISSUE TITLE
Freezes desktop

### ISSUE THREAD

**Issue by mzenker** [Nikilauz/sysmon.sh#1]
When setting the refresh rate to 0.5 seconds, my desktop freezes from time to time, and the plugin itself seems to be frozen permanently. It cannot be configured or removed. I had to remove it using the xfce settings. So I think there is a bug,,,

**Comment by Nikilauz** [comment]
The script currently measures CPU- and network-activity for 1 second, so refresh rates less than a second may cause unexpected behaviour. An update to prevent that will come soon (hopefully)...
